name: Browser Build & Web Deploy

on:
  push:
    branches: [ "ci"]

jobs:
    build:
        runs-on: lmql-ci
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: pip install -e .
            - name: Test
              run: bash scripts/wheel.sh $1
