name: Run Tests and Publish Wheel

on:
  push:
    branches: [ "ci"]

jobs:
    build:
        runs-on: lmql-ci
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: pip install -e .
            - name: Run Tests
              run: python src/lmql/tests/all.py
            - name: Package
              run: bash scripts/wheel.sh latest
