name: Run Tests and Publish Wheel

on:
  push:
    branches: [ "ci"]

jobs:
    test-with-hf-transformers:
        runs-on: lmql-ci
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: pip install -e '.[hf]' && pip install langchain
            - name: Run Tests
              env:
                OPENAI_API_KEY: ${{ secrets.LMQL_CI_OPENAI_KEY }}
              run: python src/lmql/tests/all.py
            - name: Install Packaging Dependencies
              run: pip install build twine
            - name: Package
              run: bash scripts/wheel.sh latest
