name: Run Tests and Publish Wheel

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.*'

jobs:
    test-with-hf-transformers:
        runs-on: lmql-ci
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: pip install -e '.[hf]' && pip install langchain
            # - name: Run Tests
            #   env:
            #     OPENAI_API_KEY: ${{ secrets.LMQL_CI_OPENAI_KEY }}
            #   run: python src/lmql/tests/all.py
            - name: Install Packaging Dependencies
              run: pip install build twine
            - name: Package
              env:
                VERSION: ${{ github.ref }}
              run: bash scripts/wheel.sh $VERSION
            - name: Publish
              env:
                TWINE_USERNAME: __token__
                TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
                VERSION: ${{ github.ref }}
              run: bash scripts/pypi-release.sh lmql-$VERSION
